const styles = {

  cabecalho: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 40px',
    background: 'rgba(15, 15, 35, 0.85)',
    backdropFilter: 'blur(12px)',
    borderBottom: '1px solid rgba(139, 92, 246, 0.25)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  cabecalhoLogo: {
    fontSize: '1.4rem',
    fontWeight: 700,
    background: 'linear-gradient(135deg, #a78bfa, #6366f1)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    letterSpacing: '0.5px',
  },
  cabecalhoNav: {
    display: 'flex',
    gap: '8px',
  },
  cabecalhoBotao: {
    padding: '10px 22px',
    border: '1px solid rgba(139, 92, 246, 0.3)',
    borderRadius: '10px',
    background: 'transparent',
    color: '#c4b5fd',
    fontSize: '0.95rem',
    fontFamily: 'inherit',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    fontWeight: 500,
  },
  cabecalhoBotaoAtivo: {
    padding: '10px 22px',
    border: '1px solid rgba(139, 92, 246, 0.6)',
    borderRadius: '10px',
    background: 'linear-gradient(135deg, rgba(139, 92, 246, 0.25), rgba(99, 102, 241, 0.2))',
    color: '#e0d4ff',
    fontSize: '0.95rem',
    fontFamily: 'inherit',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    fontWeight: 600,
    boxShadow: '0 0 20px rgba(139, 92, 246, 0.15)',
  },

  rodape: {
    textAlign: 'center',
    padding: '28px 40px',
    background: 'rgba(15, 15, 35, 0.85)',
    backdropFilter: 'blur(12px)',
    borderTop: '1px solid rgba(139, 92, 246, 0.25)',
    marginTop: 'auto',
  },
  rodapeLink: {
    color: '#a78bfa',
    textDecoration: 'none',
    fontSize: '0.95rem',
    fontWeight: 500,
    transition: 'color 0.3s ease',
  },
  rodapeTexto: {
    color: '#7c7c9a',
    fontSize: '0.85rem',
    marginTop: '8px',
  },


  menu: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: '16px',
    padding: '32px 20px',
  },


  botao: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    padding: '18px 24px',
    border: '1px solid rgba(139, 92, 246, 0.2)',
    borderRadius: '16px',
    background: 'rgba(30, 30, 60, 0.5)',
    backdropFilter: 'blur(8px)',
    cursor: 'pointer',
    transition: 'all 0.35s ease',
    minWidth: '140px',
    fontFamily: 'inherit',
    color: '#c4b5fd',
  },
  botaoSelecionado: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    padding: '18px 24px',
    border: '1px solid rgba(139, 92, 246, 0.6)',
    borderRadius: '16px',
    background: 'linear-gradient(135deg, rgba(139, 92, 246, 0.2), rgba(99, 102, 241, 0.15))',
    backdropFilter: 'blur(8px)',
    cursor: 'pointer',
    transition: 'all 0.35s ease',
    minWidth: '140px',
    fontFamily: 'inherit',
    color: '#e0d4ff',
    boxShadow: '0 8px 32px rgba(139, 92, 246, 0.2)',
    transform: 'translateY(-4px)',
  },
  botaoFoto: {
    width: '72px',
    height: '72px',
    borderRadius: '50%',
    objectFit: 'cover',
    border: '2px solid rgba(139, 92, 246, 0.4)',
    transition: 'border-color 0.3s ease',
  },
  botaoFotoSelecionado: {
    width: '72px',
    height: '72px',
    borderRadius: '50%',
    objectFit: 'cover',
    border: '3px solid #a78bfa',
    boxShadow: '0 0 16px rgba(167, 139, 250, 0.35)',
    transition: 'all 0.3s ease',
  },
  botaoNome: {
    fontSize: '0.95rem',
    fontWeight: 600,
    letterSpacing: '0.3px',
  },

 
  cardContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(340px, 1fr))',
    gap: '20px',
    padding: '12px 40px 40px',
    maxWidth: '1200px',
    margin: '0 auto',
    width: '100%',
    boxSizing: 'border-box',
  },
  card: {
    background: 'rgba(30, 30, 60, 0.6)',
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(139, 92, 246, 0.2)',
    borderRadius: '16px',
    padding: '24px',
    transition: 'all 0.35s ease',
  },
  cardTitulo: {
    fontSize: '1rem',
    fontWeight: 700,
    marginBottom: '6px',
    background: 'linear-gradient(135deg, #c4b5fd, #818cf8)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  cardCategoria: {
    fontSize: '0.8rem',
    color: '#7c7c9a',
    marginBottom: '14px',
    fontWeight: 500,
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  cardCodigo: {
    background: 'rgba(10, 10, 30, 0.7)',
    border: '1px solid rgba(139, 92, 246, 0.15)',
    borderRadius: '10px',
    padding: '16px',
    overflowX: 'auto',
    fontFamily: "'Fira Code', 'Cascadia Code', 'Consolas', monospace",
    fontSize: '0.85rem',
    lineHeight: '1.6',
    color: '#e0d4ff',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },


  conteudo: {
    maxWidth: '800px',
    margin: '0 auto',
    padding: '40px 20px',
  },
  conteudoTitulo: {
    fontSize: '2rem',
    fontWeight: 700,
    textAlign: 'center',
    marginBottom: '32px',
    background: 'linear-gradient(135deg, #a78bfa, #6366f1)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  conteudoItem: {
    background: 'rgba(30, 30, 60, 0.5)',
    backdropFilter: 'blur(8px)',
    border: '1px solid rgba(139, 92, 246, 0.2)',
    borderRadius: '14px',
    padding: '22px 28px',
    marginBottom: '16px',
    transition: 'all 0.3s ease',
  },
  conteudoNome: {
    fontSize: '1.15rem',
    fontWeight: 700,
    color: '#c4b5fd',
    marginBottom: '6px',
  },
  conteudoDescricao: {
    fontSize: '0.95rem',
    color: '#a0a0c0',
    lineHeight: '1.5',
  },

 
  paginaPrincipal: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  tituloSecao: {
    textAlign: 'center',
    fontSize: '1.1rem',
    color: '#7c7c9a',
    padding: '24px 20px 0',
    fontWeight: 500,
  },

  
  appContainer: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
  },
  mainContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
};

export default styles;
